/**
 * Writes dist/sw.js after the build.
 *
 * Two lists:
 * - INSTALL, saved when the worker installs: the offline page and the CSS / fonts / icons it
 *   needs, so there is always something to show without a connection. It is kept small so
 *   installing never competes with the pages a reader opens next.
 * - PRECACHE, saved afterwards in the background, one file at a time and only once the page
 *   reports the browser is idle: the app shell pages, every approved chapter and decision
 *   record, every "Why not?" comparison, the search index, and the CSS / fonts (Latin subset)
 *   / JS those pages load up front.
 * On-demand chunks such as Mermaid are not precached; the service worker saves them the first
 * time they are used.
 *
 * VERSION is a hash of the worker's code and everything precached, so any change to
 * content, assets or caching logic installs a new service worker and replaces the old cache.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';
import { readContentFiles, readDecisionFiles } from './content-files';
import { chapterHref } from '../lib/content/rules';
import { decisionHref } from '../lib/decisions/records';
import { cssLatinFonts, htmlAssetRefs, jsStaticImports } from '../lib/pwa/assets';

const INSTALL_PAGES = ['/offline'];
const SHELL_PAGES = ['/', '/roadmap', '/learn', '/search', '/advisor', '/evolution', '/playground', '/decisions', '/why-not', '/offline'];
const INSTALL_FILES = [
  '/manifest.webmanifest',
  '/favicon-32.png',
  '/favicon-48.png',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/apple-touch-icon.png',
];
const STATIC_FILES = ['/search-index.json', ...INSTALL_FILES];
const TEMPLATE = 'src/service-worker/sw.js';

export function serviceWorker(): AstroIntegration {
  let root = process.cwd();

  return {
    name: 'systemly:service-worker',
    hooks: {
      'astro:config:done': ({ config }) => {
        root = fileURLToPath(config.root);
      },
      'astro:build:done': async ({ dir, logger }) => {
        const out = fileURLToPath(dir);
        const approved = (await readContentFiles(root))
          .filter((entry) => entry.data.status === 'approved')
          .map((entry) => chapterHref(entry.data.slug));
        const records = (await readDecisionFiles(root))
          .filter((entry) => entry.data.status === 'approved')
          .map((entry) => decisionHref(entry.data.slug));
        // Comparisons are small: every built one is saved (approved, and placeholders listing the options).
        const comparisons = (await readdir(path.join(out, 'why-not'), { withFileTypes: true }).catch(() => []))
          .filter((d) => d.isDirectory())
          .map((d) => `/why-not/${d.name}`)
          .sort();
        const pages = [...SHELL_PAGES, ...approved, ...records, ...comparisons];

        const files = await assetsOf(out, pages, STATIC_FILES);
        const install = [...INSTALL_PAGES, ...[...(await assetsOf(out, INSTALL_PAGES, INSTALL_FILES))].sort()];

        const template = await readFile(path.join(root, TEMPLATE), 'utf8');
        // The worker's own code is part of the version, so a caching change also refreshes caches.
        const hash = createHash('sha256').update(template);
        let bytes = 0;
        const precacheFiles = [...pages.map(pageFile), ...[...files].map((f) => f.slice(1))].sort();
        for (const file of precacheFiles) {
          const full = path.join(out, file);
          const info = await stat(full).catch(() => undefined);
          if (!info) throw new Error(`Service worker precache: missing build output "${file}"`);
          bytes += info.size;
          hash.update(file).update(await readFile(full));
        }
        const version = hash.digest('hex').slice(0, 12);

        const precache = [...pages, ...[...files].sort()].filter((file) => !install.includes(file));
        const header =
          `// Generated by src/integrations/service-worker.ts — do not edit.\n` +
          `const VERSION = ${JSON.stringify(version)};\n` +
          `const INSTALL = ${JSON.stringify(install, null, 2)};\n` +
          `const PRECACHE = ${JSON.stringify(precache, null, 2)};\n\n`;
        await writeFile(path.join(out, 'sw.js'), header + template);

        logger.info(
          `sw.js ${version}: ${install.length} files on install, then ${precache.length} files ` +
            `(${(bytes / 1024).toFixed(0)} KB in all) saved in the background ` +
            `(${approved.length} approved ${approved.length === 1 ? 'chapter' : 'chapters'}, ` +
            `${records.length} approved decision ${records.length === 1 ? 'record' : 'records'}, ` +
            `${comparisons.length} ${comparisons.length === 1 ? 'comparison' : 'comparisons'})`,
        );
      },
    },
  };
}

/** The files the given pages load up front, following stylesheets to fonts and scripts to imports. */
async function assetsOf(out: string, pages: string[], extra: string[]): Promise<Set<string>> {
  const files = new Set(extra);
  const queue: string[] = [];
  for (const page of pages) {
    const html = await readFile(path.join(out, pageFile(page)), 'utf8');
    queue.push(...htmlAssetRefs(html));
  }
  while (queue.length > 0) {
    const ref = queue.pop()!;
    if (files.has(ref)) continue;
    files.add(ref);
    if (ref.endsWith('.css')) queue.push(...cssLatinFonts(await readFile(path.join(out, ref), 'utf8')));
    if (/\.m?js$/.test(ref)) queue.push(...jsStaticImports(await readFile(path.join(out, ref), 'utf8'), ref));
  }
  return files;
}

/** Built HTML file for a page URL (build.format "directory"). */
function pageFile(page: string): string {
  return page === '/' ? 'index.html' : `${page.slice(1)}/index.html`;
}
